# Generated by Django 6.0.2 on 2026-04-07 20:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer'), ('HOLD', 'Hold'), ('RELEASE', 'Release'), ('CAPTURE', 'Capture'), ('REVERSAL', 'Reversal')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('FAILED', 'Failed')], default='POSTED', max_length=20)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionWalletLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SOURCE', 'Source'), ('DESTINATION', 'Destination'), ('AFFECTED', 'Affected')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_links', to='transactions.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_links', to='wallets.wallet')),
            ],
            options={
                'db_table': 'transaction_wallet_links',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['actor_user'], name='transaction_actor_u_8a6b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='transaction_type_840495_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reversal_of'], name='transaction_reversa_a8ccfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('actor_user', 'type', 'idempotency_key'), name='uq_tx_actor_type_idemkey'),
        ),
        migrations.AddIndex(
            model_name='transactionwalletlink',
            index=models.Index(fields=['transaction'], name='transaction_transac_128270_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionwalletlink',
            index=models.Index(fields=['wallet'], name='transaction_wallet__08f0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionwalletlink',
            index=models.Index(fields=['transaction', 'role'], name='transaction_transac_869503_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionwalletlink',
            constraint=models.UniqueConstraint(fields=('transaction', 'wallet'), name='uq_tx_wallet_unique'),
        ),
    ]
