# Generated by Django 6.0.2 on 2026-04-07 20:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
                'indexes': [models.Index(fields=['user'], name='wallets_user_id_9fb6cf_idx'), models.Index(fields=['currency'], name='wallets_currenc_378bd9_idx'), models.Index(fields=['status'], name='wallets_status_5720bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'currency'), name='uq_wallet_user_currency')],
            },
        ),
    ]
